/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    DraftWorkbenchDialog: typeof import('./src/components/dialog/DraftWorkbenchDialog.vue')['default']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    FormItemLabel: typeof import('./src/components/FormItemLabel.vue')['default']
    HeaderBox: typeof import('./src/components/HeaderBox.vue')['default']
    HeaderNavLine: typeof import('./src/components/HeaderNavLine.vue')['default']
    InitialPage: typeof import('./src/components/InitialPage.vue')['default']
    InitPageStepDialog: typeof import('./src/components/dialog/InitPageStepDialog.vue')['default']
    LoginDialog: typeof import('./src/components/dialog/LoginDialog.vue')['default']
    MaskLoading: typeof import('./src/components/MaskLoading.vue')['default']
    MiniMountedResizeView: typeof import('./src/components/MiniMountedResizeView.vue')['default']
    PackageStep: typeof import('./src/components/dialog/PackageStep.vue')['default']
    PrivacyStatement: typeof import('./src/components/dialog/PrivacyStatement.vue')['default']
    ProjectPlatformStep: typeof import('./src/components/dialog/ProjectPlatformStep.vue')['default']
    ProjectTree: typeof import('./src/components/ProjectTree.vue')['default']
    ResourceServiceStep: typeof import('./src/components/dialog/ResourceServiceStep.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoDialog: typeof import('./src/components/VideoDialog.vue')['default']
  }
}
