export default {
  zh: {
    titleSetting: '标题配置',
    titleName: '标题名称',
    titleWidth: '标题宽度',
    titlePos: '标题位置',
    iconColor: '图标颜色',
    iconInfo: '图标信息',
    inputSetting: '输入框配置',
    value: '初始值',
    inputWidth: '宽度',
    inputNodePos: '位置',
    inputPlaceholder: '提示信息',
    showLimit: '长度限制',
    maxLength: '最大长度',
    minLength: '最小长度',
    prefixIcon: '前置图标',
    suffixIcon: '后置图标',
    required: '必填',
    clearable: '可清空',
  },
  en: {
    titleSetting: 'Title Setting',
    titleName: 'Title Name',
    titleWidth: 'Title Width',
    titlePos: 'Title Position',
    iconColor: 'Icon Color',
    iconInfo: 'Icon Info',
    inputSetting: 'Input Setting',
    value: 'value',
    inputWidth: 'Input Width',
    inputNodePos: 'Input Position',
    inputPlaceholder: 'placeholder',
    showLimit: 'Show Limit',
    maxlength: 'Maxlength',
    minlength: 'Minlength',
    prefixIcon: 'PrefixIcon',
    suffixIcon: 'SuffixIcon',
    required: 'Required',
    clearable: 'Clearable',
  },
  ja: {
    titleSetting: '标题配置',
    titleName: '标题名称',
    titleWidth: '标题宽度',
    titlePos: '标题位置',
    iconColor: '图标颜色',
    iconInfo: '图标信息',
    inputSetting: '输入框配置',
    value: '初始值',
    inputWidth: '宽度',
    inputNodePos: '位置',
    inputPlaceholder: '提示信息',
    showLimit: '长度限制',
    maxLength: '最大长度',
    minLength: '最小长度',
    prefixIcon: '前置图标',
    suffixIcon: '后置图标',
    required: '必填',
    clearable: '可清空',
  },
}
